server:
  port: 8081

spring:
  application:
    name: kms-backend

  datasource:
    url: ${SPRING_DATASOURCE_URL:${DB_URL:jdbc:postgresql://${DATABASE_HOST:${DB_HOST:dpg-da43olv40ujc73cpl09g-a.virginia-postgres.render.com}}:${DATABASE_PORT:${DB_PORT:5432}}/${DATABASE_NAME:${DB_NAME:insakms}}${DATABASE_SSLMODE:${DB_SSLMODE:?sslmode=require}}}}
    username: ${SPRING_DATASOURCE_USERNAME:${DATABASE_USERNAME:${DB_USER:insakms_user}}}
    password: ${SPRING_DATASOURCE_PASSWORD:${DATABASE_PASSWORD:${DB_PASS:hLYoKjsf0GlpZbKCNfSDZ8aRGoR0oMYS}}}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    locations: classpath:db/migration

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URL:http://localhost:8080}/realms/kms-realm

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
